---
title: "Case Study 3: Election Prediction"
---
  
```{r, echo=FALSE, include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
```




# Learning Objectives

- continue developing skills in using models for prediction
- evaluate and update predictions based on dynamic data
- combine data on a variety of levels (national, state, individual) to predict election outcomes

# Case Study Goals
Goals of this case study are (1) to predict whether the US Senate remains in Republican control, and (2) to predict the outcomes of all NC Congressional elections (the 13 federal Representatives to Congress), including characterization of uncertainty in predictions.

PRESIDENT?  ANDY GELMAN NEW STUFF FOR ECONOMIST


We will present predictions weekly, and the final case study grading criteria will include some determined by the class. In addition, prizes will be given in a number of categories (e.g., most creative useful data source).

# Data

- [gay_marriage_megapoll.dta](decks/data/gay_marriage_megapoll.dta)
- [NC voter files](https://dl.ncsbe.gov/?prefix=data/) Note these data are processed on Sakai.
- [Cooperative Congressional Election Study](https://cces.gov.harvard.edu/pages/welcome-cooperative-congressional-election-study) 
- [Opportunity Insights Data Library](https://opportunityinsights.org/data/?geographic_level=0&topic=0&paper_id=0#resource-listing)
- See data on Sakai under Resources in the Case Study 3 folder for 2010 Census summary data and 2016 and 2018 voting data in NC

# Resources

- [Andy Gelman Interview on Election Forecasting](https://www.datacamp.com/community/blog/election-forecasting-polling) (This is a very interesting interview overall. I suggest listening to it all, but the polling/election modeling component starts about 30 minutes into the interview.)
- [Andy Gelman's Predictive Model for *The Economist*](https://projects.economist.com/us-2020-forecast/president/how-this-works)
- [North Carolina Congressional Elections Fall 2020](https://ballotpedia.org/United_States_House_of_Representatives_elections_in_North_Carolina,_2020)
- [Which districts are viewed as competitive?](https://ballotpedia.org/U.S._House_battlegrounds,_2020)
- [Why do we care about likely voters?](https://fivethirtyeight.com/features/registered-voter-polls-will-usually-overrate-democrats/)
- [FiveThirtyEight's election page]( https://fivethirtyeight.com/politics/elections/)
- [Google Street View and Voting](https://www.citylab.com/transportation/2017/12/google-street-view-data-demographics-cars-research/547436/)
- [Pickup Trucks and Voting](http://www.thedrive.com/news/16712/trump-supporting-towns-more-likely-to-be-filled-with-pickup-trucks-study-claims)

# Slides 
- [Basics of Election Prediction](decks/cs03_1.html)
- [Poststratification and Weighting](decks/cs03_2.html)
- [MRP Tutorial](decks/cs03_3.html)
                                                                                                                                                                        
                                                                                                                                                                        
                                                                                          
                                                                                                                                                            # Reports
                                                                              - Weekly predictions of the NC Congressional races starting October 12
                                                                              - Interim report 1: who votes in NC? Using the NC voter files, identify who votes in NC so that these data can be used with election surveys in order to predict outcomes of NC congressional elections. Present results in short in-class presentation and in accompanying report not to exceed 5 pages.  Results should be fully reproducible. 
                                                                                                                                                                        - Interim report 2: in 5 pages (maximum), outline your models and general strategy for predicting the outcome of the 2018 elections.
                                                                                                                                                                        - Final report: Items for Final Report
                                                                                                                                                                        + The final report itself should be structured with an introduction, description of methods (e.g., modeling and prediction strategy along with the models themselves), results (point and interval estimates of the % of votes won by each Congressional candidate, predicting the winner of each race; point and interval estimates of the probability the US House remains under Republican control). Discussion should include some evaluation of the relative predictive ability of variables in your models (e.g., maybe you predicted voter turnout as a function of pet ownership rates, but maybe pet ownership rates are not at all predictive – so we want to know which data sources you felt were most useful) as well as discussion of strengths and weaknesses of your strategy. Any visualizations should be included (or linked, if they are interactive) in the final report. The final report should contain two appendices, described below.
                                                                                                                                                                        + Appendix A: Numbered list of all models/modeling procedures, with explicit details about model purpose, model structure, and resulting estimates from each model (raw output is fine for this appendix). Reproducible code and data should also be uploaded to Sakai.
                                                                                                                                                                        + Appendix B: List of all data sets/data sources used, along with an explicit mapping from the models in Appendix A to the variables used from Appendix B in each model.
                                                                                                                                                                        
                                                                                                                                                                        
                                                                                                                                                                        - Presentation after election: discuss what went right and wrong with your modeling and assumptions based on election outcomes (e.g., winners, who voted, etc.)
                                                                                                                                                                        
                                                                                                                                                                        
                                                                                                                                                            
                                                                                                                                                                                                                                          
                                                                                                                                                                        # Prizes
                                                                                                                                                                        
                                                                                                                                                                        Prizes may be awarded in the following categories:
                                                                                                                                                                          
                                                                                                                                                                          (1) best prediction (who wins each NC house seat + House control + tiebreak of exact number of seats won by Democrats, Republicans, and others in US House of Representatives + second tiebreak of \% of vote share by winning candidate in NC 9th district)
                                                                                                                                                                        (2) most creative data source useful for prediction (e.g., Yeti sales, number of nail salons per capita, tweets)
                                                                                                                                                                        (3) most easily accessibile new data source useful for prediction
                                                                                                                                                                        (4) best interactive visualization
                                                                                                                                                                        
                                                                                                                                                                        