---
title: "STA 440: Case Studies"
output: 
  html_document:
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "STA 440: Case Studies in the Practice of Statistics"
description: "Students apply statistical analysis skills to in-depth data analysis projects ranging across diverse application areas. Students practice cutting-edge statistical methods and communicate their results both technically and non-technically via presentations and written reports. Prerequisite: STA 360. QS, W."
markup: "mmark"
---



# Welcome to STA440!

### Goal of the Course

The goal of STA 440 is to prepare you for work as a practicing statistician. Important skills required of practicing statisticians (in addition to having a great set of tools in the statistics toolbox!) include creativity, critical thinking, teamwork, the ability to identify needed new skills and to learn them with minimal direction, the ability to craft a statistical analysis plan to fit a scientific hypothesis or question, teamwork, and the ability to communicate to a variety of audiences (including other statisticians, experts in areas other than statistics, a supervisor at work, and the general public, among others). 

Lectures will include some new material you may not have seen, as well as material that you have already seen but that is often poorly understood. My goal is for you to be as prepared as possible to tackle real-world problems. This means that questions of interest will typically not be framed in much stati68+stical detail -- part of your job will be to figure out which tools to use to analyze the data. 

Flexibility, work ethic, knowledge of statistical science, pragmatism, the ability to proceed with minimal direction, professionalism, communication skills, and the willingness to try new things are all strong predictors of success in STA 440 (as well as in the working world). Don't worry if you haven't mastered all of these -- we'll work on them in class! 

### Class Meetings

<font color="#6CA0DC"><i class="fas fa-university fa-lg"></i></font> &nbsp; Zoom

<font color="#6CA0DC"><i class="fas fa-calendar-alt fa-lg"></i></font> &nbsp; MWF 10:15 - 11:30 (usually Mondays will be labs, but sometimes lab and lecture will be swapped)


### Teaching team and office hours 


Note: office hours may vary due to travel and other commitments. Revisions to office hours will be noted via e-mail and on my webpage. 

| Team member | Office hours | Location |
| ----------  | -------------------------------------         | ---- |
| [Professor Amy Herring](https://stat.duke.edu/people/amy-h-herring)  <a href="mailto:amy.herring@duke.edu" title="email"><i class="fa fa-envelope"></i></a> &nbsp;  | Fridays 2-3pm Eastern Time | Zoom (see Sakai for link) |
 [TA David Buch](https://davidbuch.github.io)  <a href="mailto:david.buch@duke.edu" title="email"><i class="fa fa-envelope"></i></a> &nbsp;  | Wednesdays 8-9pm Eastern Time | Zoom (see Sakai for link) |
 [TA Graham Tierney](https://g-tierney.github.io)  <a href="mailto:graham.tierney@duke.edu" title="email"><i class="fa fa-envelope"></i></a> &nbsp; | Mondays 12-1pm Eastern Time | Zoom (see Sakai for link) |
 
                  


### Materials

You should have access to a laptop and bring it to every class, fully charged. Texts and readings will be assigned as needed. The instructor and TA's will support computation in R and RStudio. Students are free to use any software they wish as long as reproducibility requirements are met (e.g., you could knit from R markdown).


### Topics and Important Dates

STA 440 contains a mixture of short lecture, lab, and work sessions at the usual class and lab times. Frequent mini-assignments will be provided in class and lab to check mastery and identify areas for additional focus.

Note: this schedule is approximate and is likely to be modified as the course progresses. Lab sessions will be swapped with lectures due to course timing as needed. All course and lab sessions (10:15-11:30am MWF) will be recorded. Assignments are due at 10am ET unless otherwise specified. 



|Date           |Topic                      |Deliverables     |
| ----------    | ---------------------------         | --------------- |
| August 17     | Welcome and Introductions; Case Study 1: Lifespan of World Leaders; Survival Analysis        |     |
| August 19     | How to Write a Model; Interaction; Discrimination Project    |    Getting to Know You Videos  |
| August 21     |  Discrimination Project; Survival Analysis; Individual Project Q&A     |        |
| August 24    |  Lab: MCMC  |  Popes Individual Assignment    |
| August 26  | Survival Analysis; Structure of a Data Analysis Report; Writing about Data |  |79*.
| August 28   | Work Day: Case Study 1 | Project Proposals |
| August 31  |  Lab: Text Editors; Logging in to the Duke Compute Cluster; Meetings about Project Proposals | Case Study 1  |
| September 2  | Responding to Reviews; Meetings about Project Proposals  |  Case Study 1 Peer Reviews  |
| September 4  | Report Writing: Introductions, Describing Data |  |
| September 7  | Lab: Running Jobs on the Duke Compute Cluster |    |
| September 9  | Case Study 2: Detecting Stress Using Wearables | Case Study 1 Response and Revision, Peer Evals, Reviewer Evals  |
| September 11  | Back to ANOVA: Design a Model |   |
| September 14  | Lab: Brinnae Bent, Wearables Expert | Project Introduction, Data Description, EDA |
| September 16  | Multilevel Models |  |
| September 18  |  Project Work Day | Project Peer Reviews |
| September 21  |  Lab     |   |
| September 23     | Writing a Statistical Analysis Plan |   | 
| September 25     | Writing a Statistical Analysis Plan |  |
| September 28    | Lab: CS2 and Project Q&A  |   |
| September 30   | Case Study 3: Election Prediction; Poststratification and Weighting  | Case Study 2 Due |
| October 2   |  "Mr. P"; US Election System | Case Study 2 Peer Reviews; Midsemester grades (my deliverable)  |
| October 5    |  Forecasting US Presidential Elections; Linzer Model |   |
| October 7    | Forecasting US Presidential Elections; Multilevel Logistic Models |  |
| October 9    |  | Case Study 2 Response and Revision  |
| October 12    | Forecasting Models |   | 
| October 14    |  |  |
| October 16   |  Project Presentations |  First Predictions Due   | 
| October 19    | Project Presentations | Project Methods, Analysis Plan, and Preliminary Results (DUE AT 6AM ET)  | 
| October 21    | Project Presentations | Project Peer Reviews (due 10am ET)  |
| October 23   | Project Presentations | Case Study 3: Who Votes in NC?; Updated Predictions |
| October 26    | Project Presentations | Case Study 3 Who Votes Peer Reviews  | 
| October 28   | Project Presentations |  |
| October 30   | Project Presentations | Updated Predictions |
| November 2   | Project Presentations  | Case Study 3 Due |
| November 4   | Case Study 3 Models; Highs and Lows Presentations  | |
| November 6   | Case Study 3 Models; Highs and Lows Presentations |  |
| November 9   |  | Individual Project Due |
| November 11   |  | Project Peer Reviews  | 
| November 13   | Data Science Ethics Discussion |  |
| November 16   |  | Project Response and Revision Due |
| November 19   |  | Last Day to Submit Project Revision Without Late Penalty |

